name: image-crawler
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - requests>=2.31.0
  - tqdm>=4.66.1
  - pyyaml>=6.0.1
  - loguru>=0.7.2
  - pip:
    - python-dotenv>=1.0.0
